@api=  http://localhost:3000/api/products
GET {{api}}

### add a product
POST {{api}}

Content-Type: application/json
{
    "codigo": "0245",
    "producto": "Celular",
    "precio": "5482"
}

### get product
GET {{api}}/5

### delete product 
DELETE {{api}}/6